db.Restaurant.find();
db.Restaurant.find({}, {restaurant_id:1, name:1, borough:1, cuisine:1});
db.Restaurant.find({}, {restaurant_id:1, name:1, borough:1, cuisine:1, _id:0});
db.Restaurant.find({}, {restaurant_id:1, name:1, borough:1, address:{zipcode:1}, _id:0});
db.Restaurant.find({borough: "Bronx"});
db.Restaurant.find({borough: "Bronx"}).limit(5);
db.Restaurant.find({borough: "Bronx"}).skip(5).limit(5);
db.Restaurant.find({grades:{$elemMatch: {score: {$gt: 90}}}});
db.Restaurant.find({grades:{$elemMatch: {score: {$gt: 80, $lt: 100}}}});
db.Restaurant.find({"address.coord.0": {$lt: -95.754168}});
db.Restaurant.find({$and:[{cuisine:{$not: /American/}},{grades:{$elemMatch:{score:{$gt:70}}}},{"address.coord.1": {$gt: -65.754168}}]});
db.Restaurant.find({cuisine:{$not: /American/},grades:{$elemMatch:{score:{$gt:70}}},"address.coord.1": {$gt: -65.754168}});
db.Restaurant.find({cuisine: {$not: /American/}, grades: {$elemMatch: {grade: "A"}}, borough: {$not: /Brooklyn/}}).sort({cuisine:-1});
db.Restaurant.find({name: /^Wil/},{restaurant_id:1, name:1, borough:1, cuisine:1, _id:0});
db.Restaurant.find({name: /ces$/},{restaurant_id:1, name:1, borough:1, cuisine:1, _id:0});
db.Restaurant.find({name: /Reg/},{restaurant_id:1, name:1, borough:1, cuisine:1, _id:0});
db.Restaurant.find({borough: "Bronx", cuisine: /(American|Chinese)/}, {borough:1, cuisine:1, _id:0});
db.Restaurant.find({borough: /(Staten Island|Queens|Bronx|Brooklyn)/}, {restaurant_id:1, name:1, borough:1, cuisine:1, _id:0});
db.Restaurant.find({borough: {$not: /(Staten Island|Queens|Bronx|Brooklyn)/}}, {restaurant_id:1, name:1, borough:1, cuisine:1, _id:0});
db.Restaurant.find({grades:{$elemMatch:{score:{$lt: 10}}}}, {restaurant_id:1, name:1, borough:1, cuisine:1, _id:0});
db.Restaurant.find( {$and:[{cuisine:/seafood/i}, {cuisine:{$not:/american/i}}, {cuisine:{$not:/chinese/i}}, {name: {$not:/^Wil/}}]}, {restaurant_id:1, name:1, borough:1, cuisine:1, _id:0} );
db.Restaurant.find({$and:[{grades: {$elemMatch: {grade: "A"}}},{grades:{$elemMatch:{score:11}}},{grades:{$elemMatch:{date:ISODate("2014-08-11T00:00:00Z")}}}]}, {restaurant_id:1, name:1, grades:1, _id:0});
db.Restaurant.find({"grades.1.grade": "A", "grades.1.score": "9", "grades.1.date": ISODate("2014-08-11T00:00:00Z")}, {restaurant_id:1, name:1, grades:1, _id:0});
db.Restaurant.find({$or:[{"address.coord.1": {$gt: 42}}, {"address.coord.1": {$lt: 52}}]}, {restaurant_id:1, name:1, address:1, borough:1, _id:0});
db.Restaurant.find().sort( { name: 1 } );
db.Restaurant.find().sort( { name: -1 } );
db.Restaurant.find().sort({cuisine: 1, borough: -1});
db.Restaurant.find({"address.street":{$exists:true}});
db.Restaurant.find({"address.coord":{$elemMatch: {$type : "double"}}});
db.Restaurant.find({ grades:{$elemMatch:{score:{ $mod: [ 7, 0 ] }}} },{restaurant_id:1, name:1, grades:{grade:1}, _id:0});
db.Restaurant.find({name: /mon/},{name:1, borough:1,address:{coord:1}, cuisine:1, _id:0});
db.Restaurant.find({name: /^Mad/},{name:1, borough:1,address:{coord:1}, cuisine:1, _id:0});